#!/usr/bin/env bash
# Rebuilds catalog/INDEX.md from each template's README.md "## Manifest" table.
#
# Convention (shared by every catalog/<name>/README.md, see Task 8 report for the normalization
# this convention required on the pre-existing node22-lint-test/go1.23-test READMEs):
#
#   - Title line 1: `# <name>`
#   - A description paragraph directly below the title (up to the first blank line).
#   - A `## Manifest` heading followed by one or more markdown pipe-tables. The FIRST such table
#     is a `| Field | Value |` table and MUST define a `kind` row (`solo` or `env`). It MAY also
#     define `image` (the ghcr repo path, or a note that none is published) and `tasks` (a
#     comma-separated task list, or a note that tasks are target-repo-defined). Any additional
#     rows/tables under `## Manifest` (e.g. a Component/Version table) are ignored by this parser
#     -- they're for humans, not the index.
#
# Output is deterministic: templates are processed in sorted directory-name order, and the same
# README content always produces byte-identical INDEX.md rows. Running this script twice in a row
# without touching any README yields an identical file (see tests/prune.bats).
set -euo pipefail

root="$(cd "$(dirname "$0")/.." && pwd)"
catalog="$root/catalog"
out="$catalog/INDEX.md"

if [ ! -d "$catalog" ]; then
  echo "generate-index.sh: no catalog dir at $catalog" >&2
  exit 1
fi

extract_field() {
  # $1 = readme path, $2 = field name (kind|image|tasks) -> prints the value, or empty
  local readme="$1" field="$2"
  awk -v want="$field" '
    /^## Manifest/ { in_manifest=1; next }
    in_manifest && /^##/ { in_manifest=0 }
    in_manifest && /^\|/ {
      n = split($0, cols, "|")
      key = cols[2]; gsub(/[ `]/, "", key)
      val = cols[3]; gsub(/^ +| +$/, "", val)
      if (key == want) { print val; exit }
    }
  ' "$readme"
}

extract_description() {
  # $1 = readme path -> first paragraph after the title, joined onto one line
  local readme="$1"
  awk '
    NR == 1 { next }
    /^[[:space:]]*$/ { if (found) exit; next }
    /^##/ { exit }
    { if (found) printf " "; printf "%s", $0; found = 1 }
  ' "$readme"
}

escape_pipes() {
  printf '%s' "$1" | sed 's/|/\\|/g'
}

rows=()

while IFS= read -r readme; do
  dir="$(basename "$(dirname "$readme")")"

  description="$(extract_description "$readme")"
  kind="$(extract_field "$readme" kind)"
  image="$(extract_field "$readme" image)"
  tasks="$(extract_field "$readme" tasks)"

  if [ -z "$kind" ]; then
    echo "generate-index.sh: $readme has no '## Manifest' table with a 'kind' row" >&2
    exit 1
  fi

  rows+=("| \`$dir\` | $kind | $(escape_pipes "$image") | $(escape_pipes "$tasks") | $(escape_pipes "$description") |")
done < <(find "$catalog" -mindepth 2 -maxdepth 2 -type f -name README.md | sort)

{
  echo "# Template Catalog Index"
  echo
  echo "Generated by \`scripts/generate-index.sh\` from each template's \`## Manifest\` block."
  echo "Do not hand-edit -- regenerate after any README manifest change."
  echo "(A CI job compares this file against a fresh regeneration and fails on drift.)"
  echo
  echo "| Template | Kind | Image | Tasks | Description |"
  echo "|---|---|---|---|---|"
  if [ "${#rows[@]}" -gt 0 ]; then
    printf '%s\n' "${rows[@]}"
  fi
} > "$out"
